name: animated_sliced_button
description: Animated Sliced Button Widget 
version: 1.1.1
homepage: https://github.com/emreuyguc/Flutter_animated_sliced_button

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  clippy_flutter: ^1.1.1